"""Reference pool for the allergen structure and co-sensitisation brief report.

GENERATED by code/build_refs.py from out/refs/verified.json, which
holds the PubMed ESummary and EFetch records retrieved for every cited
PMID. Do not edit by hand: add the PMID to KEYS in build_refs.py and
regenerate, or add an item with no PubMed record to MANUAL there.

Numbers in the printed list are assigned by order of first appearance
in the manuscript, by number_refs.py."""

POOL = {
    "aalberse2000":
        "Aalberse, R. C. (2000). Structural biology of allergens. Journal "
        "of Allergy and Clinical Immunology, 106(2), 228–238. "
        "https://doi.org/10.1067/mai.2000.108434",
    "blum2025":
        "Blum, M., Andreeva, A., Florentino, L. C., Chuguransky, S. R., "
        "Grego, T., Hobbs, E., et al. (2025). InterPro: the protein "
        "sequence classification resource in 2025. Nucleic Acids Research, "
        "53(D1), D444–D456. https://doi.org/10.1093/nar/gkae1082",
    "codex2003":
        "Codex Alimentarius Commission. (2003). Guideline for the conduct "
        "of food safety assessment of foods derived from recombinant-DNA "
        "plants (CAC/GL 45-2003), Annex 1: Assessment of possible "
        "allergenicity. Rome: FAO/WHO.",
    "datagouv2024":
        "Société Française d'Allergologie, & AllergoBioNet. (2024). Allergen "
        "Chip Challenge database (Version 1) [dataset]. data.gouv.fr; last "
        "updated 26 July 2024; Licence Ouverte / Open Licence 2.0. "
        "https://doi.org/10.60597/j5fe-g420",
    "dramburg2023":
        "Dramburg, S., Hilger, C., Santos, A. F., de Las Vecillas, L., "
        "Aalberse, R. C., Acevedo, N., et al. (2023). EAACI Molecular "
        "Allergology User's Guide 2.0. Pediatric Allergy and Immunology : "
        "Official Publication of the European Society of Pediatric Allergy "
        "and Immunology, 34 Suppl 28, e13854. "
        "https://doi.org/10.1111/pai.13854",
    "jumper2021":
        "Jumper, J., Evans, R., Pritzel, A., Green, T., Figurnov, M., "
        "Ronneberger, O., et al. (2021). Highly accurate protein structure "
        "prediction with AlphaFold. Nature, 596(7873), 583–589. "
        "https://doi.org/10.1038/s41586-021-03819-2",
    "kabasser2024":
        "Kabasser, S., Radauer, C., Eber, E., Haber, M. E., Hieden, K., "
        "Zieglmayer, P., et al. (2024). Cosensitization to the 3 "
        "Nonhomologous Major Cashew Allergens Ana o 1, Ana o 2, and Ana o 3 "
        "Is Caused by IgE Cross-reactivity. J Investig Allergol Clin "
        "Immunol, 34(1), 38–48. https://doi.org/10.18176/jiaci.0867",
    "martinroche2026":
        "Martinroche, G., Guemari, A., Apoil, P. A., Annesi-Maesano, I., "
        "Fromentin, E., Guilleminault, L., et al. (2026). Allergen Chip "
        "Challenge: A nationwide open database supporting allergy "
        "prediction algorithms. Journal of Allergy and Clinical Immunology, "
        "157(1), 45–55. https://doi.org/10.1016/j.jaci.2025.09.017",
    "negi2023":
        "Negi, S. S., Schein, C. H., & Braun, W. (2023). The updated "
        "Structural Database of Allergenic Proteins (SDAP 2.0) provides 3D "
        "models for allergens and incorporated bioinformatics tools. "
        "Journal of Allergy and Clinical Immunology. Global, 2(4), 100162. "
        "https://doi.org/10.1016/j.jacig.2023.100162",
    "palacin2012":
        "Palacín, A., Gómez-Casado, C., Rivas, L. A., Aguirre, J., "
        "Tordesillas, L., Bartra, J., et al. (2012). Graph based study of "
        "allergen cross-reactivity of plant lipid transfer proteins (LTPs) "
        "using microarray in a multicenter study. PloS One, 7(12), e50799. "
        "https://doi.org/10.1371/journal.pone.0050799",
    "paysan2025":
        "Paysan-Lafosse, T., Andreeva, A., Blum, M., Chuguransky, S. R., "
        "Grego, T., Pinto, B. L., et al. (2025). The Pfam protein families "
        "database: embracing AI/ML. Nucleic Acids Research, 53(D1), "
        "D523–D534. https://doi.org/10.1093/nar/gkae997",
    "pomes2018":
        "Pomés, A., Davies, J. M., Gadermaier, G., Hilger, C., Holzhauser, "
        "T., Lidholm, J., et al. (2018). WHO/IUIS Allergen Nomenclature: "
        "Providing a common language. Molecular Immunology, 100, 3–13. "
        "https://doi.org/10.1016/j.molimm.2018.03.003",
    "radauer2008":
        "Radauer, C., Bublin, M., Wagner, S., Mari, A., & Breiteneder, H. "
        "(2008). Allergens are distributed into few protein families and "
        "possess a restricted number of biochemical functions. Journal of "
        "Allergy and Clinical Immunology, 121(4), 847–52.e7. "
        "https://doi.org/10.1016/j.jaci.2008.01.025",
    "scala2010":
        "Scala, E., Alessandri, C., Bernardi, M. L., Ferrara, R., Palazzo, "
        "P., Pomponi, D., et al. (2010). Cross-sectional survey on "
        "immunoglobulin E reactivity in 23,077 subjects using an allergenic "
        "molecule-based microarray detection system. Clinical and "
        "Experimental Allergy : Journal of the British Society for Allergy "
        "and Clinical Immunology, 40(6), 911–921. "
        "https://doi.org/10.1111/j.1365-2222.2010.03470.x",
    "scala2011":
        "Scala, E., Alessandri, C., Palazzo, P., Pomponi, D., Liso, M., "
        "Bernardi, M. L., et al. (2011). IgE recognition patterns of "
        "profilin, PR-10, and tropomyosin panallergens tested in 3,113 "
        "allergic patients by allergen microarray-based technology. PloS "
        "One, 6(9), e24912. https://doi.org/10.1371/journal.pone.0024912",
    "vankempen2024":
        "van Kempen, M., Kim, S. S., Tumescheit, C., Mirdita, M., Lee, J., "
        "Gilchrist, C. L. M., et al. (2024). Fast and accurate protein "
        "structure search with Foldseek. Nature Biotechnology, 42(2), "
        "243–246. https://doi.org/10.1038/s41587-023-01773-0",
    "varadi2024":
        "Varadi, M., Bertoni, D., Magana, P., Paramval, U., Pidruchna, I., "
        "Radhakrishnan, M., et al. (2024). AlphaFold Protein Structure "
        "Database in 2024: providing structure coverage for over 214 "
        "million protein sequences. Nucleic Acids Research, 52(D1), "
        "D368–D375. https://doi.org/10.1093/nar/gkad1011",
    "zhang2004":
        "Zhang, Y., & Skolnick, J. (2004). Scoring function for automated "
        "assessment of protein structure template quality. Proteins, 57(4), "
        "702–710. https://doi.org/10.1002/prot.20264",
    "zou2026":
        "Zou, P., Fan, Y., Xie, C., Xia, W., Liu, Y., Tao, P., et al. "
        "(2026). Allergen Sensitization Profiles and Co-Sensitization "
        "Networks in Children with Allergic Rhinitis and Asthma: A "
        "Propensity Score-Matched Retrospective Study. Journal of Asthma "
        "and Allergy, 19, 1–12. https://doi.org/10.2147/JAA.S620785",
}
